### ISSUE TITLE
Thank you! 

### ISSUE THREAD

**Issue by gjtorikian** [scoutapm-sponsorships/github-sponsorships#1]
Just wanted to send y'all a note of thanks for the GitHub Sponsorship. It means a lot to me and I appreciate it! ❤️

**Comment by scoutapm-sponsorships** [comment]
You're welcome!

**Comment by geerlingguy** [comment]
I'll add on to that, you are making a huge difference in open source maintainers' lives (mine included), and I hope your leadership in that regard can be matched by other companies to help make open source software more sustainable!

**Comment by akondas** [comment]
I would also like to thank you. According to the tier you choose, I would like to include your logo and link on the site. Should it go directly to this profile (`scoutapm-sponsorships`) or maybe the main organization (`scoutapp`)?

**Comment by Siilwyn** [comment]
Thank you for becoming my first sponsor! :heart:
